# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

# http://docs.travis-ci.com/user/languages/minimal-and-generic/
language: minimal

script:
    #Verify the actual file contents are present
    - sh -c 'echo "Verifying rt.jar and src.zip are present..."; test -f ./rt.jar && test -f ./src.zip'

    #Verify that the rt.jar is a valid JAR and it isn't malformed. Also verifies the signature, if it exists
    - sh -c 'echo "Verifying rt.jar using jarsigner tool...";jarsigner -verify ./rt.jar'
    
    #Verify the license/legal files required are present
    - sh -c 'echo "Verifying license and legal files are present..."; test -f ./LICENSE && test -f ./DISCLAIMER && test -f ./THIRD_PARTY_README'
    
    #Verify that we can download rt.jar for this commit remotely using the GitHub URI
    - sh -c 'echo "Verifying rt.jar is downloadable for current commit..."; curl --output /dev/null --silent --show-error --fail --ssl --head "https://github.com/welovecoding/openjdk7-rt/raw/$(git rev-parse HEAD)/rt.jar"'

notifications:
  email: false
